### PR TITLE
Fix compilation with GCC 7.2

### LINKED ISSUE #7: compling urdfdom on ARM64 fails with tinyxml codepack error
I had to add `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` to tinyxml_cmakelists.txt in order to get urdfdom to compile on ARM64 (aarch64, ARM Cortext-53). Without it you get this error: 
```
libtinyxml.a: relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `__stack_chk_guard@@GLIBC_2.17' can not be used when making a shared object; recompile with -fPIC
```

### PR DESCRIPTION
**Pull request by BrannonKing**
Fixes #7

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Looks good to me but waiting for feedback in #7.

**Comment by dirk-thomas** [comment]
@BrannonKing If you use "Fixes #7" in the description of the ticket (rather than "Goes with issue #7") the referenced issue will be closed automatically when this PR is being merged.

**Comment by BrannonKing** [comment]
description updated

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3823/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/962/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3163/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3910/)

**Comment by dirk-thomas** [comment]
> description updated

The GitHub "magic" doesn't work if you use a full URL to the referenced issue. You need to either use "# 7" or "ros2/tinyxml_vendor # 7" (without the spaces). Afterwards you should see a dotted line indicating the "magic".

**Comment by BrannonKing** [comment]
I see it now. Thanks.

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Pull request merged**
